# Generated by Django 4.2.6 on 2024-01-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user_images/'),
        ),
    ]
