# Generated by Django 4.2.6 on 2024-02-17 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0020_destination_spotdistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('reviw_image1', models.ImageField(blank=True, default=None, null=True, upload_to='review_images/')),
                ('reviw_image2', models.ImageField(blank=True, default=None, null=True, upload_to='review_images/')),
                ('spotname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
