# Generated by Django 4.2.6 on 2024-02-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontribution', '0002_rename_reviw_image1_review_review_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='district',
            new_name='spotdistrict',
        ),
    ]
