# Generated by Django 4.2.6 on 2024-02-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontribution', '0003_rename_district_review_spotdistrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspot',
            name='new_spot_image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='new_spot_images/'),
        ),
        migrations.AlterField(
            model_name='newspot',
            name='new_spot_image1',
            field=models.ImageField(default=0, upload_to='new_spot_images/'),
            preserve_default=False,
        ),
    ]
