# Generated by Django 4.2.6 on 2024-02-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontribution', '0004_newspot_new_spot_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspot',
            name='new_spot_image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='new_spot_images/'),
        ),
    ]
