# Generated by Django 4.2.6 on 2024-02-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontribution', '0005_alter_newspot_new_spot_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspot',
            old_name='descrption',
            new_name='description',
        ),
    ]
