# Generated by Django 4.2.6 on 2024-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontribution', '0006_rename_descrption_newspot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspot',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newspot',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='spotdistrict',
            field=models.CharField(max_length=50),
        ),
    ]
