# Generated by Django 4.2.6 on 2024-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontribution', '0007_alter_newspot_description_alter_newspot_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspot',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=1500),
        ),
    ]
