# Generated by Django 4.2.6 on 2023-12-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('packagnumber', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('spotname', models.CharField(max_length=100)),
                ('landscape', models.CharField(max_length=100)),
                ('pricerequired', models.IntegerField()),
                ('timerequired', models.IntegerField()),
                ('img', models.ImageField(upload_to='set1')),
            ],
        ),
        migrations.CreateModel(
            name='Set2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('packagnumber', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('spotname', models.CharField(max_length=100)),
                ('landscape', models.CharField(max_length=100)),
                ('pricerequired', models.IntegerField()),
                ('timerequired', models.IntegerField()),
                ('img', models.ImageField(upload_to='set2')),
            ],
        ),
        migrations.CreateModel(
            name='Set3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('packagnumber', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('spotname', models.CharField(max_length=100)),
                ('landscape', models.CharField(max_length=100)),
                ('pricerequired', models.IntegerField()),
                ('timerequired', models.IntegerField()),
                ('img', models.ImageField(upload_to='set3')),
            ],
        ),
        migrations.CreateModel(
            name='Set4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('packagnumber', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('spotname', models.CharField(max_length=100)),
                ('landscape', models.CharField(max_length=100)),
                ('pricerequired', models.IntegerField()),
                ('timerequired', models.IntegerField()),
                ('img', models.ImageField(upload_to='set4')),
            ],
        ),
    ]
