# Generated by Django 4.2.6 on 2023-12-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='set2',
            name='id',
        ),
        migrations.RemoveField(
            model_name='set3',
            name='id',
        ),
        migrations.RemoveField(
            model_name='set4',
            name='id',
        ),
        migrations.AlterField(
            model_name='set1',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='set2',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='set3',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='set4',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
