# Generated by Django 4.2.6 on 2023-12-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_set1_id_remove_set2_id_remove_set3_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set1',
            old_name='sno',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='set2',
            old_name='sno',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='set3',
            old_name='sno',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='set4',
            old_name='sno',
            new_name='id',
        ),
    ]
