# Generated by Django 4.2.6 on 2023-12-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_rename_sno_set1_id_rename_sno_set2_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packageset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('packagnumber', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('spotnumber', models.IntegerField()),
                ('spotname', models.CharField(max_length=100)),
                ('landscape', models.CharField(max_length=100)),
                ('cafespot', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='packageset')),
            ],
        ),
    ]
