# Generated by Django 4.2.6 on 2023-12-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packageset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('landscape', models.CharField(max_length=100)),
                ('cafespot', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='destination')),
            ],
        ),
        migrations.CreateModel(
            name='Twodaypackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('packagnumber', models.IntegerField()),
                ('spotnumber', models.IntegerField()),
                ('spotname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Threedaypackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('packagnumber', models.IntegerField()),
                ('spotnumber', models.IntegerField()),
                ('spotname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Sixdaypackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('packagnumber', models.IntegerField()),
                ('spotnumber', models.IntegerField()),
                ('spotname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Sevendaypackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('packagnumber', models.IntegerField()),
                ('spotnumber', models.IntegerField()),
                ('spotname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Onedaypackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('packagnumber', models.IntegerField()),
                ('spotnumber', models.IntegerField()),
                ('spotname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Fourdaypackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('packagnumber', models.IntegerField()),
                ('spotnumber', models.IntegerField()),
                ('spotname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Fivedaypackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('packagnumber', models.IntegerField()),
                ('spotnumber', models.IntegerField()),
                ('spotname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
            ],
        ),
    ]
