# Generated by Django 4.2.6 on 2023-12-23 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0005_destination_twodaypackage_threedaypackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedaypackage',
            name='userpart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
