# Generated by Django 4.2.6 on 2023-12-23 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0007_alter_onedaypackage_userpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedaypackage',
            name='userpart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
