# Generated by Django 4.2.6 on 2023-12-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_onedaypackage_userpart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onedaypackage',
            options={'ordering': ['district', 'packagnumber', 'spotnumber']},
        ),
        migrations.AlterModelTableComment(
            name='onedaypackage',
            table_comment='packages for 1day tour selection',
        ),
        migrations.RemoveField(
            model_name='onedaypackage',
            name='userpart',
        ),
        migrations.AlterField(
            model_name='onedaypackage',
            name='packagnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='onedaypackage',
            name='spotnumber',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20),
        ),
    ]
