# Generated by Django 4.2.6 on 2023-12-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_onedaypackage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['spotname']},
        ),
    ]
