# Generated by Django 4.2.6 on 2023-12-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_alter_destination_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['id']},
        ),
    ]
