# Generated by Django 4.2.6 on 2023-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_alter_onedaypackage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fivedaypackage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='fourdaypackage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sevendaypackage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sixdaypackage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='threedaypackage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='twodaypackage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTableComment(
            name='fivedaypackage',
            table_comment='packages for 5day tour selection',
        ),
        migrations.AlterModelTableComment(
            name='fourdaypackage',
            table_comment='packages for 4day tour selection',
        ),
        migrations.AlterModelTableComment(
            name='sevendaypackage',
            table_comment='packages for 7day tour selection',
        ),
        migrations.AlterModelTableComment(
            name='sixdaypackage',
            table_comment='packages for 6day tour selection',
        ),
        migrations.AlterModelTableComment(
            name='threedaypackage',
            table_comment='packages for 3day tour selection',
        ),
        migrations.AlterModelTableComment(
            name='twodaypackage',
            table_comment='packages for 2day tour selection',
        ),
        migrations.AlterField(
            model_name='fivedaypackage',
            name='packagnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fivedaypackage',
            name='spotnumber',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fourdaypackage',
            name='packagnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fourdaypackage',
            name='spotnumber',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sevendaypackage',
            name='packagnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sevendaypackage',
            name='spotnumber',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sixdaypackage',
            name='packagnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sixdaypackage',
            name='spotnumber',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='threedaypackage',
            name='packagnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='threedaypackage',
            name='spotnumber',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='twodaypackage',
            name='packagnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='twodaypackage',
            name='spotnumber',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20),
        ),
    ]
