# Generated by Django 4.2.6 on 2023-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_rename_packagnumber_onedaypackage_packagenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fivedaypackage',
            old_name='packagnumber',
            new_name='packagenumber',
        ),
        migrations.RenameField(
            model_name='fivedaypackage',
            old_name='spotnumber',
            new_name='spottime',
        ),
        migrations.RenameField(
            model_name='fourdaypackage',
            old_name='packagnumber',
            new_name='packagenumber',
        ),
        migrations.RenameField(
            model_name='fourdaypackage',
            old_name='spotnumber',
            new_name='spottime',
        ),
        migrations.RenameField(
            model_name='sevendaypackage',
            old_name='packagnumber',
            new_name='packagenumber',
        ),
        migrations.RenameField(
            model_name='sevendaypackage',
            old_name='spotnumber',
            new_name='spottime',
        ),
        migrations.RenameField(
            model_name='sixdaypackage',
            old_name='packagnumber',
            new_name='packagenumber',
        ),
        migrations.RenameField(
            model_name='sixdaypackage',
            old_name='spotnumber',
            new_name='spottime',
        ),
        migrations.AddField(
            model_name='fivedaypackage',
            name='daynumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fourdaypackage',
            name='daynumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sevendaypackage',
            name='daynumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sixdaypackage',
            name='daynumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
