# Generated by Django 4.2.6 on 2024-01-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_rename_packagnumber_fivedaypackage_packagenumber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packageset',
        ),
        migrations.DeleteModel(
            name='Set1',
        ),
        migrations.DeleteModel(
            name='Set2',
        ),
        migrations.DeleteModel(
            name='Set3',
        ),
        migrations.DeleteModel(
            name='Set4',
        ),
    ]
