# Generated by Django 4.2.6 on 2024-02-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_destination_spotdistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='cafespot',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
