# Generated by Django 4.2.6 on 2024-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0022_remove_fourdaypackage_spotname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='destination',
            name='spotdistrict',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='district',
            field=models.CharField(max_length=50),
        ),
    ]
