# Generated by Django 4.2.6 on 2024-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_alter_destination_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
