# Generated by Django 4.2.6 on 2024-01-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_alter_accommodationdetailstable_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationdetailstable',
            old_name='image',
            new_name='accommodation_image',
        ),
    ]
