# Generated by Django 4.2.6 on 2024-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_rename_image_accommodationdetailstable_accommodation_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationdetailstable',
            old_name='accommodation_image',
            new_name='accommodation_image1',
        ),
        migrations.AddField(
            model_name='accommodationdetailstable',
            name='accommodation_image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='accommodation_images/'),
        ),
    ]
