# Generated by Django 4.2.6 on 2024-02-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_rename_accommodation_image_accommodationdetailstable_accommodation_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationdetailstable',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='accommodationdetailstable',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
